;; GENERATED by testdata/gen_chain_vectors.cljs — do not edit by hand.
;; Real messages from Filecoin mainnet at height 6231448, with the CIDs the
;; chain gave them. NOT regenerated in CI: the chain moves, but these
;; are history, and history does not.
(ns filecoin.chain-vectors)

(def bls-messages
 [
  {:message {"Version" 0 "To" "f05" "From" "f3ww5q2pjcxlq3igqkfxfp3wdi2rv3rvuqmtajh55swutxedglf7yj4nmnnf2qqgkwauo6lthm3v5pupae25xq" "Nonce" 51833 "Value" "0" "GasLimit" 2894483065 "GasFeeCap" "24183938" "GasPremium" "204578" "Method" 1900091594 "Params" "SUASdFJGIvAACA=="}
   :cid "bafy2bzaceae2ov4n5p56amlswghkreeb4ylya2uoecmlfi46vuiihmz42nyi2"}
  {:message {"Version" 0 "To" "f05" "From" "f3ww5q2pjcxlq3igqkfxfp3wdi2rv3rvuqmtajh55swutxedglf7yj4nmnnf2qqgkwauo6lthm3v5pupae25xq" "Nonce" 51834 "Value" "0" "GasLimit" 2789887033 "GasFeeCap" "25090621" "GasPremium" "202393" "Method" 1900091594 "Params" "SeD0dFIGCG4PJA=="}
   :cid "bafy2bzacec626df326sb2nsmxampvz6ejebw2f3ekpex5pt53qqvqknemq77a"}
  {:message {"Version" 0 "To" "f05" "From" "f3ww5q2pjcxlq3igqkfxfp3wdi2rv3rvuqmtajh55swutxedglf7yj4nmnnf2qqgkwauo6lthm3v5pupae25xq" "Nonce" 51835 "Value" "0" "GasLimit" 2870716523 "GasFeeCap" "24384156" "GasPremium" "204276" "Method" 1900091594 "Params" "RkDedVIGCg=="}
   :cid "bafy2bzacedx4towb2lgmsp44xgv6o55zrkynncv3g6lm7uqmskzl3ao3xhbdm"}
  {:message {"Version" 0 "To" "f03151456" "From" "f3qaiq5qoayped3pzvftuzzqxfms3shknhew4wylpolu6w7un2sbwzj4qc7hiho6tnl622qjxn5ya5jvxchuma" "Nonce" 35331 "Value" "0" "GasLimit" 28476311 "GasFeeCap" "175584541129" "GasPremium" "202154" "Method" 5 "Params" "hQWBggBAgYINWMCCqBjKSD3JRJtmeuYHmnV1XE5y63nNzYo2/l9gB3lv2ZDiTffUny7rPUdc4NbZiS+C2Q2DCB//w9Oj7qBTLQ9WYw2ZfjeUaWRz7GzJk3O7uQZdf4bnlVxGMjVKWkjbptoSZAQtvzmNs0NtMD+2z3lH3JlqN7loyu2gbgO0k2PnlmIkSmL3NWKMxuTrUx0WYZOs3+eDQflf9IkQR4QEUl9+Pk9T2mtM9X2eKHoy90gDHRmjsAO0jXyXbDoVbEK6rWwaAF8Vf1ggChKU+iT2JOlcAhYvnKvWIh0dhVG2F4llZoFwgHifCfA="}
   :cid "bafy2bzacec5bptrnnbvhoekydlc4fettgucfya2wcotpcqqer5xrkijkd53ja"}
  {:message {"Version" 0 "To" "f03276663" "From" "f3rklkvnkijgse2dhewvp4piplnsf7ciup6jm7til3rpam473vjznge6y5gr27k4zvbh7rpjue77i7t2kctuza" "Nonce" 71762 "Value" "0" "GasLimit" 32039917 "GasFeeCap" "43739562" "GasPremium" "202025" "Method" 5 "Params" "hQaBggFAgYINWMCD4EhghRZIZT2HAC3PUdxV/GnUWDxq1pXBgnWID2yIuGZjpu/xDAEKlfiuKUHUPwGMH0BltulKQsTr1UQD0LZWCrAwOaiKAvr7NNdt/RA1o51F4OmUpLtDtS1+p1igphcHDRZr0IncsgH/d640FJYb1Qu5O02pfv9kfOQdEEqXaqdefdwc3Zm5HOaVF+RvrACtwgiuSQgcjQPxvttnEYDidq87H3XsS6LYceYqFqUN+7Ar7I6/cRjK6RshrUGAuW0aAF8VfFggoCNSyN7UvlYokC2KI4J6Nuq0ctmx8457v0V42n2S5RA="}
   :cid "bafy2bzacebeypqbjqv5nd3vvl263ylv7hldxvswo3pyddjlqc2l5qf43ylx2s"}
  {:message {"Version" 0 "To" "f03559995" "From" "f3uea4zrqstza5p4jaf3nz5pj555bgcnyvf2pfdrlw7w4wh5nvi2xc6r6jqssucxpagew6mqndebhrrcwq3xla" "Nonce" 12360 "Value" "0" "GasLimit" 41073657 "GasFeeCap" "121732525545" "GasPremium" "200955" "Method" 5 "Params" "hReCggBAggFAgYINWQGAsmSbRE3R7U8oUtgRyDFap8O3lylaGBUJLPF4pZUXTqvJv4LsahAowrXPhozSPSX7g2HvfxRtuAPDS8wTLDjHeaBprm0sydKIZFEcgBp4hNoiZl3igdzpIrf2NASiE76yAA6Tht9b37n6QrzXquRFUCgECsccqrQxnokkdVsjXGU1Pr2s7YbFulsAFiXHF4eKp5MqxVYat4xWr90q0732iFI392j8TgfJ/EICdy67nuuICeHbN2n9o+3SMQjxxPQYgv2nCn4hWWZmg5lcg1xVt3WDI3QGBXXR5N7NLlUoZandaD1oFXJl77wNDWJkCsvkmNvhm+bxrHan2TWnXIMbszzFDbX9k+VFyXccqlDPMmwXfl2GrI0ar0Rw71mayOMoDyeJD9BGpUUIpsREecQDmjJxr42lQnW4G3E9DDsczsgPi81x6kY+XqPDYP2U6XcCub/LXl73kSj0Ls1lX533xz2+1F/ftQdAUolCeOsi/PsDp+Ijm6EfBqx0l+w1ca/DGgBfFXdYIMQ1Vbp/YjBuvNkvvkbK7pmsf6ev/Y6GhHX+LgV1TCTQ"}
   :cid "bafy2bzacebi2jywy5p5365bonykvwzslclsbgyzcuhjrffv5nrjc4mzz5dvdy"}
 ])

;; :message-cid is the CID of the message alone; :signed-cid is the
;; CID of the [message signature] wrapper. For secp256k1 the chain
;; names the message by the second one.
(def secp256k1-messages
 [
  {:message {"Version" 0 "To" "f410fxloqxewby4oqfz6ved3eycdwkoh2evl7wlysraq" "From" "f410fidn3lrg4okfz2xzdirfb4vcj2zk44are2csftlq" "Nonce" 39952 "Value" "0" "GasLimit" 159021185 "GasFeeCap" "4690638" "GasPremium" "4690638" "Method" 3844450837 "Params" "WIRFwLktAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAK0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAF8gmwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="}
   :signature {:type 3 :data "Age3km4hLpIQZldla4hA/UdFuonXVKM8uFXGG/63wjgVFB1rruxy1wV+GWv8PkLJWmCS650yOS8lxZ91DDjukZsCmA=="}
   :message-cid "bafy2bzaceax4fqctmyanmdtilv4ngbzdgy25k4s6iaof3iwhujbjtmnd2omdu"
   :signed-cid "bafy2bzacecwdp4wtuaa5j5nmvgibfgq2tygitlixdzdjc7mklrfezgqazx3ic"}
  {:message {"Version" 0 "To" "f410feoy6aghqro4yenelcwug52jg527x6tnkxl36cyi" "From" "f410f2goyjr33xoibs4pemcbq4mijgorbbw5kppht2qq" "Nonce" 28038 "Value" "0" "GasLimit" 43087347 "GasFeeCap" "9177898" "GasPremium" "202126" "Method" 3844450837 "Params" "WMSHW8i2AAAAAAAAAAAAAAAAgLmNOqCf//JVw7pKJBER/xJi8EUAAAAAAAAAAAAAAACECFAgM8QY4bvJfOmsSOVSjzcanwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB/////////////////////////////////////////////////////////////////////////////////////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAVGA"}
   :signature {:type 3 :data "ZfvXF/9z1mOdjeIwGL6pMZaKqux0SEZiw0cPOkJLpu9AjX3uqRv83fThQvD8obvxU7cR4lruDCVuVsc9M1iRywA="}
   :message-cid "bafy2bzacedgkjumjihi3pydinqmo2iu5bz656eubzm4mul7gg7lyavnqjvm2a"
   :signed-cid "bafy2bzacecsqtje7pimxe2dldnhwe4q4keq6diibwlbmhzpok6hycwaintbds"}
  {:message {"Version" 0 "To" "f1scnuhrkelqmmzlxznes5sfu47ovr5srkyqtpdca" "From" "f1h4ssetvnj2vpugsuzptl4swlgfunw7oa3eik54a" "Nonce" 84679 "Value" "4327203941000000000000" "GasLimit" 6000000 "GasFeeCap" "1890700000" "GasPremium" "150000" "Method" 0 "Params" nil}
   :signature {:type 1 :data "Vng/6QvHj2CsstnvRiksM5iE3gOEvSSy8PwSo2AuzLpTXciOqtLKER5j/gKgDpbjLTA1XtOH02rPWkZR+xc+sgE="}
   :message-cid "bafy2bzaceavead4yce64nxuuduevhrawhrhbfdxaeh4xuwz25e6lo532h7svo"
   :signed-cid "bafy2bzacecx3fou6ysqminhuhhgwi4vkcqtyhpuyix7ize2gcjfh3qog5gnfk"}
  {:message {"Version" 0 "To" "f410fxloqxewby4oqfz6ved3eycdwkoh2evl7wlysraq" "From" "f410fidn3lrg4okfz2xzdirfb4vcj2zk44are2csftlq" "Nonce" 39952 "Value" "0" "GasLimit" 159021185 "GasFeeCap" "4690638" "GasPremium" "4690638" "Method" 3844450837 "Params" "WIRFwLktAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAK0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAF8gmwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="}
   :signature {:type 3 :data "Age3km4hLpIQZldla4hA/UdFuonXVKM8uFXGG/63wjgVFB1rruxy1wV+GWv8PkLJWmCS650yOS8lxZ91DDjukZsCmA=="}
   :message-cid "bafy2bzaceax4fqctmyanmdtilv4ngbzdgy25k4s6iaof3iwhujbjtmnd2omdu"
   :signed-cid "bafy2bzacecwdp4wtuaa5j5nmvgibfgq2tygitlixdzdjc7mklrfezgqazx3ic"}
 ])

