;; GENERATED by testdata/gen_vectors.cljs — do not edit by hand.
;; Source: filecoin-project/go-address, address_test.go.
;;
;; These are upstream's vectors, not this library's. An address
;; implementation that only agrees with itself is worth nothing.
(ns filecoin.vectors)

(def id-addresses
 [
  {:id 0 :testnet "t00"}
  {:id 1 :testnet "t01"}
  {:id 10 :testnet "t010"}
  {:id 150 :testnet "t0150"}
  {:id 499 :testnet "t0499"}
  {:id 1024 :testnet "t01024"}
  {:id 1729 :testnet "t01729"}
  {:id 999999 :testnet "t0999999"}
 ])

(def secp256k1-addresses
 [
  {:input "049402fac37e6432a416a3a0ca5426b5185ab3b24f6134efa25ce487c82d2e4e13bf452511e0d2245421f8613bc10d72fa216666a96c3bc13920d3ff233fd0bc05" :testnet "t15ihq5ibzwki2b4ep2f46avlkrqzhpqgtga7pdrq" :mainnet "f15ihq5ibzwki2b4ep2f46avlkrqzhpqgtga7pdrq"}
  {:input "047687b910379bf28cbe3aea674b12000c6b7dba46ffc05f6c94fe2a22bbcc2602ff7f5c76f21ca55d36959152b0e1e887917c393576eef093f61ebd3ad06f7fda" :testnet "t12fiakbhe2gwd5cnmrenekasyn6v5tnaxaqizq6a" :mainnet "f12fiakbhe2gwd5cnmrenekasyn6v5tnaxaqizq6a"}
  {:input "04defdd01001efb86e01ded5ce34f847a73a14819ee641bcb60bb92993596f05dc2d605f2985f8d125812dac4163a396349b23c11cc2ff359de54be287ea62319b" :testnet "t1wbxhu3ypkuo6eyp6hjx6davuelxaxrvwb2kuwva" :mainnet "f1wbxhu3ypkuo6eyp6hjx6davuelxaxrvwb2kuwva"}
  {:input "0403ed12c814b6b10d2ee09d95b4688db2d180d0a9a37a6b6a7db63d29811ee9730479d8ef9139e91249cabd393291cfe5d277ba76de45e3e085a37681bf3645d2" :testnet "t1xtwapqc6nh4si2hcwpr3656iotzmlwumogqbuaa" :mainnet "f1xtwapqc6nh4si2hcwpr3656iotzmlwumogqbuaa"}
  {:input "04f796819a8e271631af7c189797b545d60225936147e6010e6562b3ce9efe8b10144161a91ed0b4ec890800253fa6fc20ac90fbf1fbf27130a4ecc3e403b70576" :testnet "t1xcbgdhkgkwht3hrrnui3jdopeejsoatkzmoltqy" :mainnet "f1xcbgdhkgkwht3hrrnui3jdopeejsoatkzmoltqy"}
  {:input "0442832bf87cce9ea345b90350de7d3495859ca449059c5e88dde74285dffb9ec01ebabc5fc86268cfeaeba7ae05bfb8d68eb75a5268782cf86fc8702bef8a1fe0" :testnet "t17uoq6tp427uzv7fztkbsnn64iwotfrristwpryy" :mainnet "f17uoq6tp427uzv7fztkbsnn64iwotfrristwpryy"}
 ])

(def actor-addresses
 [
  {:input "76128190cdf068d1418044acc03e0b6781970d60" :testnet "t24vg6ut43yw2h2jqydgbg2xq7x6f4kub3bg6as6i" :mainnet "f24vg6ut43yw2h2jqydgbg2xq7x6f4kub3bg6as6i"}
  {:input "2cafb8e2e06bba98ea657c5cf5f42023aa23e88e" :testnet "t25nml2cfbljvn4goqtclhifepvfnicv6g7mfmmvq" :mainnet "f25nml2cfbljvn4goqtclhifepvfnicv6g7mfmmvq"}
  {:input "022c9e0ea29d8f40c56abec35c8d587da0a64c18" :testnet "t2nuqrg7vuysaue2pistjjnt3fadsdzvyuatqtfei" :mainnet "f2nuqrg7vuysaue2pistjjnt3fadsdzvyuatqtfei"}
  {:input "dfec030e204f0f59d80f1d5ee91dfd066d7f63bd" :testnet "t24dd4ox4c2vpf5vk5wkadgyyn6qtuvgcpxxon64a" :mainnet "f24dd4ox4c2vpf5vk5wkadgyyn6qtuvgcpxxon64a"}
  {:input "3d3a89e8ddab547832716c6d468c3560c9f47fd8" :testnet "t2gfvuyh7v2sx3patm5k23wdzmhyhtmqctasbr23y" :mainnet "f2gfvuyh7v2sx3patm5k23wdzmhyhtmqctasbr23y"}
 ])

(def bls-addresses
 [
  {:input "ad58df696e2d4e91ea86c881e938ba4ea81b395e12797b84b9cf314b9546705e839c7a99d606b247ddb4f9ac7a3414dd" :testnet "t3vvmn62lofvhjd2ugzca6sof2j2ubwok6cj4xxbfzz4yuxfkgobpihhd2thlanmsh3w2ptld2gqkn2jvlss4a" :mainnet "f3vvmn62lofvhjd2ugzca6sof2j2ubwok6cj4xxbfzz4yuxfkgobpihhd2thlanmsh3w2ptld2gqkn2jvlss4a"}
  {:input "b3294f0a2e29e0c66ebc235d2fedca5697bf784af605c75af608e6a63d5cd38ea85ca8989e0efde9188b382f9372460d" :testnet "t3wmuu6crofhqmm3v4enos73okk2l366ck6yc4owxwbdtkmpk42ohkqxfitcpa57pjdcftql4tojda2poeruwa" :mainnet "f3wmuu6crofhqmm3v4enos73okk2l366ck6yc4owxwbdtkmpk42ohkqxfitcpa57pjdcftql4tojda2poeruwa"}
  {:input "96a1a3e4ea7a14d49985e661b22401d44fed402d1d0925b243c923589c0fbc7e32cd04e29ed78d15d37d3aaa3fe6da33" :testnet "t3s2q2hzhkpiknjgmf4zq3ejab2rh62qbndueslmsdzervrhapxr7dftie4kpnpdiv2n6tvkr743ndhrsw6d3a" :mainnet "f3s2q2hzhkpiknjgmf4zq3ejab2rh62qbndueslmsdzervrhapxr7dftie4kpnpdiv2n6tvkr743ndhrsw6d3a"}
  {:input "86b454258c589475f7d16f5aac018a79f6c1169d20fc33921dd8b5ce1cac6c348f90a3603624f6aeb91b64518c2e8095" :testnet "t3q22fijmmlckhl56rn5nkyamkph3mcfu5ed6dheq53c244hfmnq2i7efdma3cj5voxenwiummf2ajlsbxc65a" :mainnet "f3q22fijmmlckhl56rn5nkyamkph3mcfu5ed6dheq53c244hfmnq2i7efdma3cj5voxenwiummf2ajlsbxc65a"}
  {:input "a7726b038022f75a384617585360cee629070a2d9d28712965e5f26ecc40858382803724ed34f2720336f09db631f074" :testnet "t3u5zgwa4ael3vuocgc5mfgygo4yuqocrntuuhcklf4xzg5tcaqwbyfabxetwtj4tsam3pbhnwghyhijr5mixa" :mainnet "f3u5zgwa4ael3vuocgc5mfgygo4yuqocrntuuhcklf4xzg5tcaqwbyfabxetwtj4tsam3pbhnwghyhijr5mixa"}
 ])

;; namespace is a string: the last case is 2^63-1, which this
;; library refuses rather than rounds (see filecoin.varint).
(def delegated-addresses
 [
  {:namespace "32" :subaddress "ffffffffff" :expected "f432f77777777x32lpna"}
  {:namespace "9223372036854775807" :subaddress "" :expected "f49223372036854775807fiic6zsy"}
  {:namespace "9223372036854775807" :subaddress "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000" :expected "f49223372036854775807faaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaahwgiuam"}
 ])

