#!/usr/bin/env nbb
;; Snapshot real messages off Filecoin mainnet, with the CIDs the chain gave
;; them, into test/filecoin/chain_vectors.cljc.
;;
;; This is the only check that actually proves the serialiser. Everything
;; else in the suite compares this library to constants; these compare it to
;; the network. If `filecoin.message/encode` puts a field in the wrong place,
;; or encodes an attoFIL amount as anything other than sign-magnitude bytes,
;; the recomputed CID will not be the CID mainnet recorded — and no amount of
;; internal round-tripping would have noticed.
;;
;; The secp256k1 entries carry two CIDs, because a signed message has two:
;; the message's own, and the signed wrapper's. Which one names the message
;; on chain depends on the signature type (see `filecoin.signature/cid`).
;;
;; UNLIKE gen_vectors.cljs, this is NOT re-run in CI. The chain moves, so a
;; regeneration would return different messages and a diff would always
;; fail. What it produces is a permanent snapshot: mainnet history does not
;; change, so these CIDs are correct forever.
;;
;;   nbb testdata/gen_chain_vectors.cljs > test/filecoin/chain_vectors.cljc
(ns gen-chain-vectors
  (:require [clojure.string :as str]))

(def endpoint "https://api.node.glif.io/rpc/v1")
(def want-bls 6)
(def want-secp 4)

(defn- rpc [method params]
  (-> (js/fetch endpoint
                #js {:method "POST"
                     :headers #js {"content-type" "application/json"}
                     :body (js/JSON.stringify
                            (clj->js {:jsonrpc "2.0" :method method
                                      :params params :id 1}))})
      (.then #(.json %))
      (.then (fn [r]
               (if-let [e (aget r "error")]
                 (throw (ex-info (str "rpc: " (js/JSON.stringify e)) {}))
                 (aget r "result"))))))

(defn- emit-message
  "A Lotus message object as an EDN map with string keys — the shape
  `filecoin.rpc/json->message` consumes."
  [m]
  (str "{\"Version\" " (aget m "Version")
       " \"To\" " (pr-str (aget m "To"))
       " \"From\" " (pr-str (aget m "From"))
       " \"Nonce\" " (aget m "Nonce")
       " \"Value\" " (pr-str (aget m "Value"))
       " \"GasLimit\" " (aget m "GasLimit")
       " \"GasFeeCap\" " (pr-str (aget m "GasFeeCap"))
       " \"GasPremium\" " (pr-str (aget m "GasPremium"))
       " \"Method\" " (aget m "Method")
       " \"Params\" " (if-let [p (aget m "Params")] (pr-str p) "nil")
       "}"))

(defn -main []
  (-> (rpc "Filecoin.ChainHead" [])
      (.then
       (fn [head]
         (let [blocks (take 4 (aget head "Cids"))]
           (-> (js/Promise.all
                (clj->js (map #(rpc "Filecoin.ChainGetBlockMessages" [%]) blocks)))
               (.then
                (fn [results]
                  (let [bls (->> results
                                 (mapcat #(array-seq (aget % "BlsMessages")))
                                 (take want-bls))
                        secp (->> results
                                  (mapcat #(array-seq (aget % "SecpkMessages")))
                                  (take want-secp))]
                    (println
                     (str
                      ";; GENERATED by testdata/gen_chain_vectors.cljs — do not edit by hand.\n"
                      ";; Real messages from Filecoin mainnet at height "
                      (aget head "Height") ", with the CIDs the\n"
                      ";; chain gave them. NOT regenerated in CI: the chain moves, but these\n"
                      ";; are history, and history does not.\n"
                      "(ns filecoin.chain-vectors)\n\n"
                      "(def bls-messages\n [\n"
                      (str/join
                       "\n"
                       (map (fn [m]
                              (str "  {:message " (emit-message m)
                                   "\n   :cid " (pr-str (aget (aget m "CID") "/")) "}"))
                            bls))
                      "\n ])\n\n"
                      ";; :message-cid is the CID of the message alone; :signed-cid is the\n"
                      ";; CID of the [message signature] wrapper. For secp256k1 the chain\n"
                      ";; names the message by the second one.\n"
                      "(def secp256k1-messages\n [\n"
                      (str/join
                       "\n"
                       (map (fn [sm]
                              (let [m (aget sm "Message")
                                    sig (aget sm "Signature")]
                                (str "  {:message " (emit-message m)
                                     "\n   :signature {:type " (aget sig "Type")
                                     " :data " (pr-str (aget sig "Data")) "}"
                                     "\n   :message-cid " (pr-str (aget (aget m "CID") "/"))
                                     "\n   :signed-cid " (pr-str (aget (aget sm "CID") "/")) "}")))
                            secp))
                      "\n ])\n")))))))))))

(-main)
