#!/usr/bin/env nbb
;; Regenerate test/filecoin/vectors.cljc from go-address's own test file.
;;
;; The address vectors are not this workspace's to invent: an implementation
;; that agrees with itself about what `f1…` means is worth nothing. So they
;; are lifted verbatim from `filecoin-project/go-address`'s
;; `address_test.go` — the same discipline `io-storj-node/testdata` follows
;; by regenerating its vectors from Storj's own code, and the reason this
;; parses Go source rather than computing anything.
;;
;;   nbb testdata/gen_vectors.cljs > test/filecoin/vectors.cljc
(ns gen-vectors
  (:require [clojure.string :as str]))

(def source
  "https://raw.githubusercontent.com/filecoin-project/go-address/master/address_test.go")

(def max-uvarint63 "9223372036854775807")

(defn- hexify [ints]
  (apply str (map #(let [h (.toString % 16)] (if (= 1 (count h)) (str "0" h) h))
                  ints)))

(defn- go-bytes->hex
  "`4, 148, 2, …` (whitespace and newlines anywhere) → a hex string.

  Go writes these both ways — the key vectors are decimal, the delegated
  sub-addresses are `0xff` — and `parseInt(\"0xff\", 10)` is 0, not an
  error, so the radix has to be chosen rather than defaulted."
  [s]
  (->> (str/split s #",")
       (map str/trim)
       (remove str/blank?)
       (map #(if (str/starts-with? % "0x")
               (js/parseInt (subs % 2) 16)
               (js/parseInt % 10)))
       hexify))

(defn- section
  "The body of a Go func, by name."
  [src fname]
  (let [start (str/index-of src (str "func " fname "("))
        end (str/index-of src "\nfunc " (inc start))]
    (subs src start (or end (count src)))))

(defn- key-vectors
  "The `{[]byte{…}, \"t…\", \"f…\"}` triples in a section."
  [src fname]
  (let [body (section src fname)
        re (js/RegExp. "\\{\\[\\]byte\\{([^}]*)\\},\\s*\"([tf][0-9][a-z0-9]+)\",\\s*\"([tf][0-9][a-z0-9]+)\"" "g")]
    (loop [out []]
      (if-let [m (.exec re body)]
        (recur (conj out {:input (go-bytes->hex (aget m 1))
                          :testnet (aget m 2)
                          :mainnet (aget m 3)}))
        out))))

(defn- id-vectors [src]
  (let [body (section src "TestVectorsIDAddress")
        re (js/RegExp. "\\{uint64\\((\\d+)\\),\\s*\"([tf]0\\d+)\"" "g")]
    (loop [out []]
      (if-let [m (.exec re body)]
        (recur (conj out {:id (js/parseInt (aget m 1) 10) :testnet (aget m 2)}))
        out))))

(defn- delegated-vectors [src]
  (let [body (section src "TestDelegatedAddress")
        re (js/RegExp.
            "\\{(\\d+|varint\\.MaxValueUvarint63),\\s*(\\[\\]byte\\{([^}]*)\\}|make\\(\\[\\]byte,\\s*MaxSubaddressLen\\)),\\s*\"(f4[^\"]+)\"" "g")]
    (loop [out []]
      (if-let [m (.exec re body)]
        (let [ns-raw (aget m 1)
              subaddr (if (str/starts-with? (aget m 2) "make")
                        (apply str (repeat 54 "00"))
                        (go-bytes->hex (or (aget m 3) "")))]
          (recur (conj out {:namespace (if (str/includes? ns-raw "MaxValue")
                                         max-uvarint63
                                         ns-raw)
                            :subaddress subaddr
                            :expected (aget m 4)})))
        out))))

(defn- emit-map [m ks]
  (str "  {" (str/join " " (map (fn [k]
                                  (let [v (get m k)]
                                    (str k " " (if (string? v) (pr-str v) v))))
                                ks))
       "}"))

(defn -main []
  (-> (js/fetch source)
      (.then #(.text %))
      (.then
       (fn [src]
         (let [out
               (str
                ";; GENERATED by testdata/gen_vectors.cljs — do not edit by hand.\n"
                ";; Source: filecoin-project/go-address, address_test.go.\n"
                ";;\n"
                ";; These are upstream's vectors, not this library's. An address\n"
                ";; implementation that only agrees with itself is worth nothing.\n"
                "(ns filecoin.vectors)\n\n"
                "(def id-addresses\n [\n"
                (str/join "\n" (map #(emit-map % [:id :testnet]) (id-vectors src)))
                "\n ])\n\n"
                "(def secp256k1-addresses\n [\n"
                (str/join "\n" (map #(emit-map % [:input :testnet :mainnet])
                                    (key-vectors src "TestVectorSecp256k1Address")))
                "\n ])\n\n"
                "(def actor-addresses\n [\n"
                (str/join "\n" (map #(emit-map % [:input :testnet :mainnet])
                                    (key-vectors src "TestVectorActorAddress")))
                "\n ])\n\n"
                "(def bls-addresses\n [\n"
                (str/join "\n" (map #(emit-map % [:input :testnet :mainnet])
                                    (key-vectors src "TestVectorBLSAddress")))
                "\n ])\n\n"
                ";; namespace is a string: the last case is 2^63-1, which this\n"
                ";; library refuses rather than rounds (see filecoin.varint).\n"
                "(def delegated-addresses\n [\n"
                (str/join "\n" (map #(emit-map % [:namespace :subaddress :expected])
                                    (delegated-vectors src)))
                "\n ])\n")]
           (println out))))))

(-main)
